spring.application.name=email-writer-sb
gemini.api.key=AIzaSyDiEiWS7xpSrMzDf_pbhqOcq5vEh6KYEiA
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=

